#pragma once

#define PROTOTYPE_DRIVER_TAG		'BEEF'
#define PROTOTYPE_DRIVER_DEVICE	0x8000

#define PROTOTYPE_DRIVER_UNPROTECT_PROCESS			CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define PROTOTYPE_DRIVER_PROTECT_PROCESS				CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define PROTOTYPE_DRIVER_PROCESS_PRIVILEGE			CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define PROTOTYPE_DRIVER_ENUM_PROCESS_CALLBACKS		CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x810, METHOD_NEITHER, FILE_ANY_ACCESS)
#define PROTOTYPE_DRIVER_ZERO_PROCESS_CALLBACK		CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x811, METHOD_NEITHER, FILE_ANY_ACCESS)
#define PROTOTYPE_DRIVER_ADD_PROCESS_CALLBACK		CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x812, METHOD_NEITHER, FILE_ANY_ACCESS)

#define PROTOTYPE_DRIVER_ENUM_DSE					CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x820, METHOD_NEITHER, FILE_ANY_ACCESS)
#define PROTOTYPE_DRIVER_DISABLE_DSE					CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x821, METHOD_NEITHER, FILE_ANY_ACCESS)
#define PROTOTYPE_DRIVER_ENABLE_DSE					CTL_CODE(PROTOTYPE_DRIVER_DEVICE, 0x822, METHOD_NEITHER, FILE_ANY_ACCESS)